#define INPUT_PRIORITY_MAX 9
#define INPUT_PRIORITY_HIGH 7
#define INPUT_PRIORITY_NORMAL 5
#define INPUT_PRIORITY_LOW 3
#define INPUT_PRIORITY_MIN 1

#define SCRIPT_LOG "script_log.txt"

#define UI_EVENT_QUIT 0